### ISSUE TITLE
Randomness on Avalanche

### ISSUE THREAD

**Issue by loic001** [pooltogether/v4-core#257]
Can someone explain me how the randomness is generated on avalanche? I can't find the RNGService implementation for Avalanche: https://v4-docs.pooltogether.com/protocol/deployments/mainnet

Looks like rng services are not deployed on avalanche: https://v4.docs.pooltogether.com/protocol/contracts/rng-services/

Chainlink VRF is not available on avalanche so that explains it but what method was chosen by pooltogether?

Thanks a lot for your help

**Comment by PierrickGT** [comment]
Hello @loic001,
We are using an Open Zeppelin autotask to push the draw result from Ethereum mainnet to Avalanche and Polygon.
Once Chainlink VRF V2 is available on these networks, we will update our architecture to compute the random number directly on these chains.

**Comment by loic001** [comment]
great thanks for your answer
